## Importing the required libraries

In [45]:
import pandas as pd

## Data Acquisition

In [46]:
df = pd.read_csv(r"C:\Users\Aalhad Ramteke\Downloads\Unemployment in India.csv")

## EDA

In [47]:
df.head() #displays the first 5 rows of the dataset

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),Area
0,Andhra Pradesh,31-05-2019,Monthly,3.65,11999139.0,43.24,Rural
1,Andhra Pradesh,30-06-2019,Monthly,3.05,11755881.0,42.05,Rural
2,Andhra Pradesh,31-07-2019,Monthly,3.75,12086707.0,43.50,Rural
3,Andhra Pradesh,31-08-2019,Monthly,3.32,12285693.0,43.97,Rural
4,Andhra Pradesh,30-09-2019,Monthly,5.17,12256762.0,44.68,Rural

In [48]:
df.tail() #displays the last 5 rows of the dataset

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),Area
763,NaN,NaN,NaN,NaN,NaN,NaN,NaN
764,NaN,NaN,NaN,NaN,NaN,NaN,NaN
765,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
767,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df.shape #displays the number of rows and columns in the dataset

(768, 7)

In [50]:
df.info() #displays information about the dataset

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Region                                    740 non-null    str
 1    Date                                     740 non-null    str
 2    Frequency                                740 non-null    str
 3    Estimated Unemployment Rate (%)          740 non-null    float64
 4    Estimated Employed                       740 non-null    float64
 5    Estimated Labour Participation Rate (%)  740 non-null    float64
 6   Area                                      740 non-null    str
dtypes: float64(3), str(4)
memory usage: 66.1 KB

## Missing value treatment

In [53]:
df.isnull().any() #displays whether there are any missing values in the dataset

Region                                      True
 Date                                       True
 Frequency                                  True
 Estimated Unemployment Rate (%)            True
 Estimated Employed                         True
 Estimated Labour Participation Rate (%)    True
Area                                        True
dtype: bool

In [51]:
df.isnull().sum() #displays the number of missing values in each column

Region                                      28
 Date                                       28
 Frequency                                  28
 Estimated Unemployment Rate (%)            28
 Estimated Employed                         28
 Estimated Labour Participation Rate (%)    28
Area                                        28
dtype: int64

In [54]:
df.dropna(inplace=True) #removes any rows with missing values from the dataset

In [56]:
df.isnull().any()

Region                                      False
 Date                                       False
 Frequency                                  False
 Estimated Unemployment Rate (%)            False
 Estimated Employed                         False
 Estimated Labour Participation Rate (%)    False
Area                                        False
dtype: bool

In [55]:
df.isnull().sum()

Region                                      0
 Date                                       0
 Frequency                                  0
 Estimated Unemployment Rate (%)            0
 Estimated Employed                         0
 Estimated Labour Participation Rate (%)    0
Area                                        0
dtype: int64

## Data Filteration

In [73]:
regions = df['Region'].unique() #displays the unique values in the 'Region' column
print(regions)

<ArrowStringArray>
[  'Andhra Pradesh',            'Assam',            'Bihar',
     'Chhattisgarh',            'Delhi',              'Goa',
          'Gujarat',          'Haryana', 'Himachal Pradesh',
  'Jammu & Kashmir',        'Jharkhand',        'Karnataka',
           'Kerala',   'Madhya Pradesh',      'Maharashtra',
        'Meghalaya',           'Odisha',       'Puducherry',
           'Punjab',        'Rajasthan',           'Sikkim',
       'Tamil Nadu',        'Telangana',          'Tripura',
    'Uttar Pradesh',      'Uttarakhand',      'West Bengal',
       'Chandigarh']
Length: 28, dtype: str

In [76]:
# filters the dataset to only include rows where the 'Area' column is equal to 'Rural'
rural_data = df[df['Area'] == 'Rural'] # filters the dataset to only include rows where the 'Area' column is equal to 'Rural'
print(rural_data)

             Region         Date Frequency  Estimated Unemployment Rate (%)  \
0    Andhra Pradesh   31-05-2019   Monthly                             3.65
1    Andhra Pradesh   30-06-2019   Monthly                             3.05
2    Andhra Pradesh   31-07-2019   Monthly                             3.75
3    Andhra Pradesh   31-08-2019   Monthly                             3.32
4    Andhra Pradesh   30-09-2019   Monthly                             5.17
..              ...          ...       ...                              ...
354     West Bengal   29-02-2020   Monthly                             3.78
355     West Bengal   31-03-2020   Monthly                             7.02
356     West Bengal   30-04-2020   Monthly                            18.32
357     West Bengal   31-05-2020   Monthly                            18.43
358     West Bengal   30-06-2020   Monthly                             4.94

     Estimated Employed  Estimated Labour Participation Rate (%)   Area
0            11999139.0                                    43.24  Rural
1            11755881.0                                    42.05  Rural
2            12086707.0                                    43.50  Rural
3            12285693.0                                    43.97  Rural
4            12256762.0                                    44.68  Rural
..                  ...                                      ...    ...
354          26093009.0                                    49.51  Rural
355          25097812.0                                    49.18  Rural
356          17639370.0                                    39.27  Rural
357          19115772.0                                    42.53  Rural
358          21225887.0                                    40.44  Rural

[359 rows x 7 columns]

In [75]:
# filters the dataset to only include rows where the 'Area' column is equal to 'Urban'
urban_data = df[df['Area'] == 'Urban'] 
print(urban_data)

             Region         Date Frequency  Estimated Unemployment Rate (%)  \
373  Andhra Pradesh   31-05-2019   Monthly                             6.09
374  Andhra Pradesh   30-06-2019   Monthly                             3.80
375  Andhra Pradesh   31-07-2019   Monthly                             5.64
376  Andhra Pradesh   31-08-2019   Monthly                             4.61
377  Andhra Pradesh   30-09-2019   Monthly                             6.01
..              ...          ...       ...                              ...
749     West Bengal   29-02-2020   Monthly                             7.55
750     West Bengal   31-03-2020   Monthly                             6.67
751     West Bengal   30-04-2020   Monthly                            15.63
752     West Bengal   31-05-2020   Monthly                            15.22
753     West Bengal   30-06-2020   Monthly                             9.86

     Estimated Employed  Estimated Labour Participation Rate (%)   Area
373           4788661.0                                    37.45  Urban
374           4824630.0                                    36.76  Urban
375           4657443.0                                    36.10  Urban
376           4743179.0                                    36.29  Urban
377           4733996.0                                    36.69  Urban
..                  ...                                      ...    ...
749          10871168.0                                    44.09  Urban
750          10806105.0                                    43.34  Urban
751           9299466.0                                    41.20  Urban
752           9240903.0                                    40.67  Urban
753           9088931.0                                    37.57  Urban

[381 rows x 7 columns]

In [68]:
# Keep rows where the unemployment rate is greater than 50
df.columns = df.columns.str.strip()
df_high = df[df['Estimated Unemployment Rate (%)'] > 50] 
print(df_high)
print(df_high.shape) #displays the number of rows and columns in the filtered dataset

         Region         Date Frequency  Estimated Unemployment Rate (%)  \
145   Jharkhand   31-05-2020   Monthly                            55.10
242  Puducherry   30-04-2020   Monthly                            74.51
287  Tamil Nadu   30-04-2020   Monthly                            53.19
412       Bihar   30-04-2020   Monthly                            58.77
530   Jharkhand   30-04-2020   Monthly                            61.48
531   Jharkhand   31-05-2020   Monthly                            70.17
627  Puducherry   30-04-2020   Monthly                            76.74
628  Puducherry   31-05-2020   Monthly                            75.00

     Estimated Employed  Estimated Labour Participation Rate (%)   Area
145           3315038.0                                    37.03  Rural
242             49420.0                                    46.79  Rural
287           5086200.0                                    33.05  Rural
412           1400962.0                                    34.94  Urban
530           1054829.0                                    39.92  Urban
531            830347.0                                    40.49  Urban
627             68122.0                                    35.54  Urban
628             64538.0                                    31.25  Urban
(8, 7)

In [70]:
# Keep rows where the unemployment rate is less than 30
df.columns = df.columns.str.strip()
df_high = df[df['Estimated Unemployment Rate (%)'] < 30] 
print(df_high)
print(df_high.shape) #displays the number of rows and columns in the filtered dataset

             Region         Date Frequency  Estimated Unemployment Rate (%)  \
0    Andhra Pradesh   31-05-2019   Monthly                             3.65
1    Andhra Pradesh   30-06-2019   Monthly                             3.05
2    Andhra Pradesh   31-07-2019   Monthly                             3.75
3    Andhra Pradesh   31-08-2019   Monthly                             3.32
4    Andhra Pradesh   30-09-2019   Monthly                             5.17
..              ...          ...       ...                              ...
749     West Bengal   29-02-2020   Monthly                             7.55
750     West Bengal   31-03-2020   Monthly                             6.67
751     West Bengal   30-04-2020   Monthly                            15.63
752     West Bengal   31-05-2020   Monthly                            15.22
753     West Bengal   30-06-2020   Monthly                             9.86

     Estimated Employed  Estimated Labour Participation Rate (%)   Area
0            11999139.0                                    43.24  Rural
1            11755881.0                                    42.05  Rural
2            12086707.0                                    43.50  Rural
3            12285693.0                                    43.97  Rural
4            12256762.0                                    44.68  Rural
..                  ...                                      ...    ...
749          10871168.0                                    44.09  Urban
750          10806105.0                                    43.34  Urban
751           9299466.0                                    41.20  Urban
752           9240903.0                                    40.67  Urban
753           9088931.0                                    37.57  Urban

[698 rows x 7 columns]
(698, 7)

## Summary Statistics

In [80]:
print("\nSummary Statistics")
df.describe()

Summary Statistics

,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%)
count,740.000000,7.400000e+02,740.000000
mean,11.787946,7.204460e+06,42.630122
std,10.721298,8.087988e+06,8.111094
min,0.000000,4.942000e+04,13.330000
25%,4.657500,1.190404e+06,38.062500
50%,8.350000,4.744178e+06,41.160000
75%,15.887500,1.127549e+07,45.505000
max,76.740000,4.577751e+07,72.570000